### ISSUE TITLE
Stackoverflow when using too much data in OjAlgo

### ISSUE THREAD

**Issue by DanielMartensson** [optimatika/ojAlgo#256] opened 2020-05-21 15:19 UTC
Hi!

I have got this issue. It's not OjAlgo's fault. But I just want to tell that OjAlgo can give you a  stackoverflow error if you use too much data.

```
Exception in thread "main" java.lang.StackOverflowError
        at org.ojalgo.matrix.store.LogicalStore.physical(LogicalStore.java:56)
```

Perhaps int has been used instead of long?

**How to reproduce this problem:**

1. Download jFaces.jar https://github.com/DanielMartensson/jFaces
2. Download mnist_png.tar.gz https://github.com/myleott/mnist_png
3. Extrakt mnist_png.tar.gz
4. Call jFaces.jar where you specify the location of the training set.

`java -Xmx5000M -jar jFaces.jar -f "/home/hp/Téléchargements/mnist_png/training" -b "/home/hp/model.ser"`

**Comment by apete** [comment] 2020-05-21 17:41
Show me the full stack trace instead and/or show me how you use the `LogicalBuilder`.

A StackOverflowError is not caused by too much data. It's most likely caused by a programming mistake.

**Comment by apete** [comment] 2020-05-22 06:58
With that repmat implementation; how many time is the input matrix repeated? If `m` and `n` are very large then that design if not good, and is probably what's causing this.

**Comment by apete** [comment] 2020-05-22 09:30
You can try this: https://github.com/optimatika/ojAlgo/pull/257

**Comment by DanielMartensson** [comment] 2020-05-22 13:42
> You can try this: #257

But this method does not exist? 

```
static public Primitive64Matrix repmat(Primitive64Matrix X, int m, long n) {

	   X.logical().repmat(m, n) 

```

**Comment by apete** [comment] 2020-05-27 07:03
I gave you a link to a pull request where it does exist. It is now merged to the `develop` branch.

**Comment by DanielMartensson** [comment] 2020-05-27 17:26
> I gave you a link to a pull request where it does exist. It is now merged to the `develop` branch.

Good. Than I will want untill the next OjAlgo update. Is there any schedule for that?

**Comment by apete** [comment] 2020-05-27 19:11
No, there's no schedule. Just build from source if you want to try that new feature.

**Closed by apete** 2020-05-27 19:11 UTC
