### ISSUE TITLE
Pom.xml for version 35.0

### ISSUE THREAD

**Issue by EHadoux** [optimatika/ojAlgo#11] opened 2015-12-14 17:13 UTC
Hello, the pom.xml file for version 35.0 is flawed.
You may want to fix it.
Cheers.

**Comment by apete** [comment] 2015-12-14 21:25
You cannot alter existing artifacts in any way. So I cannot fix or remove 35.0. The problem is fixed with 35.0.1

I made a typo in the pom, upload validation didn't catch it, and maven functions regardless. Other build tools and/or xml parsers have problems.

Why do you want to use v35?

**Comment by EHadoux** [comment] 2015-12-14 22:29
Oh okay, I see.
The fact is that I want to use a lib that explicitly link to 35.0. I manage to bypass it by excluding the dependency but it will blow up as soon as the code will use yours.
I'll see with the guy using your lib to update the dependency.
Thanks!

**Comment by apete** [comment] 2015-12-14 23:10
The only difference between 35.0 and 35.0.1 is that I fixed the pom.

**Closed** 2015-12-16 16:44 UTC
